package app.Controller;

import app.Model.Role;
import app.Model.User;
import app.Repository.RoleRepository;
import app.Repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after Application path)
public class UserController {
	// This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private final UserRepository userRepository;
	private final RoleRepository roleRepository;

	@Autowired
	public UserController(UserRepository userRepository, RoleRepository roleRepository) {
		this.userRepository = userRepository;
		this.roleRepository = roleRepository;
	}

	@PostMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestBody User user) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		if(user.getName().isEmpty()|| user.getPassword().isEmpty()||user.getUsername().isEmpty()){
			return "User Parameter is missing";
		}

		long userRoleId = user.getRole().getId();
		Role role = roleRepository.findOne(userRoleId);

		if(role == null){
			return "Role not found";
		}

		User newUser = new User();
		newUser.setName(user.getName());
		newUser.setUsername(user.getUsername());
		newUser.setPassword(user.getPassword());
		newUser.setRole(role);
		userRepository.save(newUser);
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
